<?php
	
	if (! $nav_bg)
		$nav_bg = "#000";
	if (! $nav_gradient_top)
		$nav_gradient_top = "#000";
	if (! $nav_gradient_bottom)
		$nav_gradient_bottom = "#000";
	if (! $nav_active_gradient_top)
		$nav_active_gradient_top = "#000";
	if (! $nav_active_gradient_bottom)
		$nav_active_gradient_bottom = "#000";
	if (! $nav_bd)
		$nav_bd = "#000";
	if (! $nav_icon_colour)
		$nav_icon_colour = "#eee";
	if (! $nav_active_icon_colour)
		$nav_active_icon_colour = "#fff";
	if (! $banner_colour)
		$banner_colour = "#000";
	if (! $link_colour)
		$link_colour = "#fff";
	if (! $bgcolour)
		$bgcolour = "#000";
	if (! $toolicon_colour)
		$toolicon_colour = "#eee";
	if (! $toolicon_activecolour)
		$toolicon_activecolour = "#fff";
	if (! $item_colour)
		$item_colour = "rgba(0,0,0,0.8)";
	if (! $comment_item_colour)
		$comment_item_colour = "rgba(0,0,0,0.4)";
	if (! $comment_border_colour)
		$comment_border_colour = "rgba(0,0,0,0.8)";
	if (! $font_colour)
		$font_colour = "#fff";
	if (! $converse_width)
		$converse_width = "1024";
